[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.19"

[rpc_endpoints]
hoodi = "https://rpc.hoodi.ethpandaops.io/"

[etherscan]
hoodi = { key = "", url = "https://explorer.hoodi.ethpandaops.io/" }